// ABI de OfertaCaptacao (niara-contracts-PMEs/src/captacao/OfertaCaptacao.sol) — escrow de uma
// captação primária (Resolução CVM 88): aportar/encerrar/resgatarCotas/reembolsar/
// liberarParaEmissor, ver CLAUDE.md ("Backend (Supabase)" documenta o fluxo Supabase mock; este
// fluxo é o real, on-chain, em Sepolia). Extraída diretamente de
// niara-contracts-PMEs/out/OfertaCaptacao.sol/OfertaCaptacao.json (forge build), não escrita à
// mão — nomes de função/erro conferidos contra o .sol fonte antes de fixar qualquer parâmetro.
export const ofertaCaptacaoAbi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "AGENTE_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BPS_DENOMINADOR",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TAXA_BPS_MAXIMA",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "UNIDADE_COTA",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "aportadoPor",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "aportar",
    inputs: [{ name: "valor", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "cancelar", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "capacidadeRestante",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cotasDe",
    inputs: [{ name: "investidor", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cotasResgatadas",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  { type: "function", name: "despausar", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "emissorWallet",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  { type: "function", name: "encerrar", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "estado",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "enum OfertaCaptacao.Estado" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "gateway",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      {
        name: "params",
        type: "tuple",
        internalType: "struct IOfertaCaptacao.InitParams",
        components: [
          { name: "token", type: "address", internalType: "address" },
          { name: "gateway", type: "address", internalType: "address" },
          { name: "registro", type: "address", internalType: "address" },
          { name: "moeda", type: "address", internalType: "address" },
          { name: "emissorWallet", type: "address", internalType: "address" },
          { name: "protocoloWallet", type: "address", internalType: "address" },
          { name: "metaMinima", type: "uint256", internalType: "uint256" },
          { name: "metaMaxima", type: "uint256", internalType: "uint256" },
          { name: "precoPorCota", type: "uint256", internalType: "uint256" },
          { name: "prazo", type: "uint256", internalType: "uint256" },
          { name: "tetoPorInvestidor", type: "uint256", internalType: "uint256" },
          { name: "taxaBps", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "liberarParaEmissor",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "metaMaxima",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "metaMinima",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "moeda",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  { type: "function", name: "pausar", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "prazo",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "precoPorCota",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocoloWallet",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "recursosLiberados",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reembolsado",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  { type: "function", name: "reembolsar", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "registro",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IRegistroInvestidorQualificado" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "resgatarCotas",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "taxaBps",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tetoPorInvestidor",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "token",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IParticipacaoToken" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalArrecadado",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Aporte",
    inputs: [
      { name: "investidor", type: "address", indexed: true, internalType: "address" },
      { name: "valor", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "totalArrecadadoAtual", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CotasResgatadas",
    inputs: [
      { name: "investidor", type: "address", indexed: true, internalType: "address" },
      { name: "cotas", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [{ name: "version", type: "uint64", indexed: false, internalType: "uint64" }],
    anonymous: false,
  },
  { type: "event", name: "OfertaCancelada", inputs: [], anonymous: false },
  {
    type: "event",
    name: "OfertaEncerrada",
    inputs: [
      { name: "resultado", type: "uint8", indexed: false, internalType: "enum OfertaCaptacao.Estado" },
      { name: "totalArrecadado", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Paused",
    inputs: [{ name: "account", type: "address", indexed: false, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "RecursosLiberados",
    inputs: [
      { name: "emissorWallet", type: "address", indexed: true, internalType: "address" },
      { name: "valorEmissor", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "protocoloWallet", type: "address", indexed: true, internalType: "address" },
      { name: "taxa", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Reembolso",
    inputs: [
      { name: "investidor", type: "address", indexed: true, internalType: "address" },
      { name: "valor", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [{ name: "account", type: "address", indexed: false, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "error",
    name: "AporteNaoMultiploDoPreco",
    inputs: [
      { name: "valor", type: "uint256", internalType: "uint256" },
      { name: "precoPorCota", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "EncerramentoPrematuro", inputs: [] },
  { type: "error", name: "EnforcedPause", inputs: [] },
  {
    type: "error",
    name: "ExcedeMetaMaxima",
    inputs: [
      { name: "solicitado", type: "uint256", internalType: "uint256" },
      { name: "disponivel", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ExcedeTetoInvestidor",
    inputs: [
      { name: "solicitado", type: "uint256", internalType: "uint256" },
      { name: "teto", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "ExpectedPause", inputs: [] },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  { type: "error", name: "JaReembolsado", inputs: [] },
  { type: "error", name: "JaResgatado", inputs: [] },
  {
    type: "error",
    name: "MetasInvalidas",
    inputs: [
      { name: "metaMinima", type: "uint256", internalType: "uint256" },
      { name: "metaMaxima", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "NadaAReembolsar", inputs: [] },
  { type: "error", name: "NadaAResgatar", inputs: [] },
  { type: "error", name: "NaoAutorizado", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
  { type: "error", name: "OfertaNaoAberta", inputs: [] },
  { type: "error", name: "OfertaNaoEncerradaComFalha", inputs: [] },
  { type: "error", name: "OfertaNaoEncerradaComSucesso", inputs: [] },
  { type: "error", name: "PrazoExpirado", inputs: [] },
  {
    type: "error",
    name: "PrazoInvalido",
    inputs: [{ name: "prazo", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "PrecoInvalido", inputs: [] },
  { type: "error", name: "RecursosJaLiberados", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "TaxaExcedeMaximo",
    inputs: [
      { name: "taxaBps", type: "uint256", internalType: "uint256" },
      { name: "maximo", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "ZeroAddress", inputs: [] },
] as const;
